# fly.toml app configuration file generated for who-owns-what on 2023-08-04T22:57:44-05:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = "who-owns-what"
primary_region = "ord"
kill_signal = "SIGTERM"
swap_size_mb = 512

[build]

[deploy]
  release_command = "/app/bin/migrate"

[env]
  PHX_HOST = "who-owns-what.fly.dev"
  PORT = "8080"

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = true
  auto_start_machines = true
  min_machines_running = 0
  processes = ["app"]
  [http_service.concurrency]
    type = "connections"
    hard_limit = 1000
    soft_limit = 1000
