name: Update parcel data and networks

on:
  on: workflow_dispatch
  schedule:
    - cron:  '0 1 * * *'

env:
  GEOCODIO_API_KEY: ${{ secrets.GEOCODIO_API_KEY_SECRET }}
  GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

jobs:
  update-networks:
    runs-on: ubuntu-latest
    timeout-minutes: 30
    steps:
      - name: Set up R
        uses: r-lib/actions/setup-r@v2

      - name: Install packages
        uses: r-lib/actions/setup-r-dependencies@v2
        with:
          packages: |
            any::tidyverse 
            any::igraph
            any::tidygraph
            any::ggraph
            any::stringi
            any::tidygeocoder

      - name: Check out repository
        uses: actions/checkout@v3

      - name: Update data
        run: Rscript -e 'source("processing-scripts/fetch-mprop.R")'
        run: Rscript -e 'source("processing-scripts/mprop-standardize-addresses.R")'
        run: Rscript -e 'source("processing-scripts/subset-wdfi-in-mprop.R")'
        run: Rscript -e 'source("processing-scripts/wdfi-standardize-addresses.R")'
        run: Rscript -e 'source("processing-scripts/identify-owner-networks.R")'
        run: Rscript -e 'source("processing-scripts/update-network-graph-svgs.R")'

      - name: Commit results
        run: |
          git config --local jdjohn215@gmail.com "actions@github.com"
          git config --local jdjohn215 "GitHub Actions"
          git git commit -a 'Data updated' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
